# Dependabot configuration
version: 2
updates:

  # Maintain peer dependency via npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "Wednesday"
      time: "15:00"
      timezone: "America/Cancun"
    labels:
      - "review"
      - "dependencies"
      - "peer"
    commit-message:
      prefix: "build(deps-peer)"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "widen"
    allow:
      - dependency-name: "eslint"
    ignore:
      # ignore all eslint updates of minor and patch
      - dependency-name: "eslint"
        update-types: ["version-update:semver-minor"]


  # Maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "review"
      - "github-actions"
      - "ci"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
