#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

[ -z "$LOG_PREFIX" ] && LOG_PREFIX="[.husky/post-merge]"

. "$(dirname "$0")/hook-utils.sh"

update_npm_dependencies() {
  # derived from https://gist.github.com/taurus227/28960de89e6c43bb3d492125368f1224
  local changed_files=""
  local output=""
  local lockfiles=()
  local NEEDS_INSTALL=true

  changed_files="$(git diff-tree -r --name-only --diff-filter=M --no-commit-id ORIG_HEAD HEAD)"

  if output="$(replay "$changed_files" | grep "package-lock.json")"; then
    log "CHANGE DETECTED: 'package-lock.json'"
    log "Lock files rarely merge properly. Deleting and re-generating it..."

    lockfiles=("$output")            # make array of filepaths
    rm "${lockfiles[@]}"

  elif replay "$changed_files" | grep --quiet "package.json"; then
    log "CHANGE DETECTED: 'package.json'"
    log "Dependencies might of changed, lets make sure we are g2g!"
  else
    NEEDS_INSTALL=false
  fi

  if [ "$NEEDS_INSTALL" == true ]; then
    if ! command -v npm &>/dev/null; then
      error "ERROR: NPM not found on \$PATH, however 'npm install' is desired. Please accomplish manually."
      return 1
    fi

    if ! explicit_run_cmd "npm install --prefer-offline --no-fund --no-audit"; then
      error "ERROR: Dependency installation failed."
      error "You will need to perform an install manually to continue."
      return 1
    fi

    changed_files="$(git diff --name-only --diff-filter=d)"
    if output="$(replay "$changed_files" | grep "package-lock.json")"; then
      log "ALL FIXED! package-lock.json needed a refresh."

      lockfiles=("$output")            # make array of filepaths
      git add -- "${lockfiles[@]}"
      
      for lockfile in "${lockfiles[@]}"; do
        log "STAGED: $lockfile"
      done
      
      local filenoun="file"
      if [ "${#lockfiles[@]}" -gt 1 ]; then
        filenoun="${filenoun}s"
      fi
      log "Please commit the newly generated $filenoun for the team!"
    fi
  fi
}

update_npm_dependencies
