#!/bin/sh
# git-hook: pre-push
# --------------------------------------

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

[ -z "$LOG_PREFIX" ] && LOG_PREFIX="[.husky/pre-push]"

# shellcheck source=.husky/hook-utils.sh
. "$(dirname "$0")/hook-utils.sh"

env_cleanup() {
  unset -v remote_origin_name current_branch tracked_branch npm_config_loglevel
  unset -f env_cleanup
  cleanup
}

remote_origin_name="$1"
# remote_origin_location="$2"

if ! current_branch="$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')"; then
  error "Unable to detect current branch"
  exit 1
fi

if ! tracked_branch="$(git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null)"; then
  # branch is not currently tracking an upstream branch ref
  if ! printf '%s\n' "$current_branch" | grep -qE "^(master|main)$"; then
    env_cleanup && exit 0
  fi
  log "EVENT: Detected a push to ${remote_origin_name}/${current_branch}"
elif ! printf '%s\n' "$tracked_branch" | grep -qE "^${remote_origin_name}/(master|main)$"; then
  env_cleanup && exit 0
else
  log "EVENT: Detected a push to ${tracked_branch}"
fi

log "Running test suite just-in-case, we don't want to break anything!"
log "This will only take a minute..."
export npm_config_loglevel=silent
if ! npm test; then
  error "Test suite failed! It's a good thing, we checked!"
  error "Good Luck!"
  exit 1
fi

env_cleanup
