#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NODE_ENV=production

LOG_PREFIX="[.husky/pre-commit]"

. "$(dirname "$0")/hook-utils.sh"

log "$> npm run lint"
if ! npm run lint; then
  error "ERROR: Dirty code detected!"
  error "Fix the lint errors before committing to the repository."
  exit -1
fi
